stages:
  prepare:
    cmd: uv run src/prepare.py data/raw/dataset.csv data/processed
    deps:
      - data/raw/dataset.csv
      - src/prepare.py
    outs:
      - data/processed

  optimize:
    cmd: uv run src/optimize.py
    deps:
      - data/processed
      - src/optimize.py
      - config/